name: medix_mobile
description: Medix Digital Hospital Platform - Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.0.0

  # Network
  dio: ^5.4.3

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Serialization
  json_annotation: ^4.9.0
  intl: ^0.19.0

  # UI
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  fl_chart: ^0.68.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/