apiVersion: v1
kind: Secret
metadata:
  name: medix-secrets
  namespace: medix
type: Opaque
stringData:
  DATABASE_URL: "postgresql://medix_admin:CHANGE_ME@medix-staging-db.xxxxx.us-east-1.rds.amazonaws.com:5432/medix"
  REDIS_URL: "redis://medix-staging-redis.xxxxx.cache.amazonaws.com:6379"
  JWT_SECRET: "production-jwt-secret-minimum-32-chars-long-change-this"
  SENDGRID_API_KEY: ""
  TWILIO_ACCOUNT_SID: ""
  TWILIO_AUTH_TOKEN: ""